#!/usr/bin/env python
# -*- coding: utf-8 -*- 

import time
import sys
from optparse import OptionParser
from apns import APNs, Frame, Payload

reload(sys)  
sys.setdefaultencoding('utf8')

parser = OptionParser(usage="%prog [option] device_token content")
parser.parse_args()

if len(sys.argv) != 3:
    parser.print_help()
    sys.exit()

apns = APNs(use_sandbox=True, cert_file='/etc/push/cert.pem', key_file='/etc/push/key.pem')

# Send a notification
token = sys.argv[1]
content = sys.argv[2]

payload = Payload(alert=content, sound="default", badge=0)
apns.gateway_server.send_notification(token, payload)

# Send an iOS 10 compatible notification
#payload = Payload(alert="Hello World!", sound="default", badge=1, mutable_content=True)
#apns.gateway_server.send_notification(token_hex, payload)
#
## Send multiple notifications in a single transmission
#frame = Frame()
#identifier = 1
#expiry = time.time()+3600
#priority = 10
#frame.add_item(token_hex, payload, identifier, expiry, priority)
#apns.gateway_server.send_notification_multiple(frame)
