#!/usr/bin/env python
# -*- coding: utf-8 -*-
# flake8: noqa

from qiniu import Auth, put_file, etag, urlsafe_base64_encode
import qiniu.config
import os
import sys
from optparse import OptionParser
import time

parser = OptionParser(usage="%prog [option] expires(s)")
parser.parse_args()

if len(sys.argv) == 1:
	expires=3600
else:
	expires=int(sys.argv[1])

access_key = os.environ["QINIU_ACCESS_KEY"]
secret_key = os.environ["QINIU_SECRET_KEY"]
q = Auth(access_key, secret_key)
bucket = os.environ["QINIU_BUCKET"]

# please get time first to ensure expire time valid
print "%d %s" % (int(time.time())+expires, q.upload_token(bucket, expires=expires))