#!/usr/bin/env python
# -*- coding: utf-8 -*-
# flake8: noqa

from qiniu import Auth, put_file, etag, urlsafe_base64_encode
import qiniu.config
import os
import sys
from optparse import OptionParser
import time

parser = OptionParser(usage="%prog [option] file")
parser.parse_args()

if (len(sys.argv) != 2):
    parser.print_usage()

file = sys.argv[1]
os.system('source /etc/profile.d/robot.sh')

access_key = os.environ["QINIU_ACCESS_KEY"]
secret_key = os.environ["QINIU_SECRET_KEY"]
q = Auth(access_key, secret_key)
bucket = os.environ["QINIU_BUCKET"]

token = q.upload_token(bucket, expires=3600)
try:
    key = os.path.basename(file)
    ret,info = put_file(token, key, file)
    print "%s/%s" % ( os.environ["QINIU_HOST"], key)
except:
    print ""


