#!/bin/bash

source /etc/profile.d/robot.sh

content=''
if [ $# -ge 1 ];then
    content="$@"
else
    OLDIFS=$IFS
    IFS=$'\x0A'
    content=`cat`
    IFS=$OLDIFS
fi

#vol=`kd app vol`
kd app vol 50 > /dev/null
file="/tmp/say.mp3"
pi t2a "$content" > $file
chmod 666 $file >/dev/null 2>&1
#mpg123  -a hw:0,0 -o alsa $file
#mplayer -af volume=-40 $file 
#nohup mplayer -af volume=-30 $file < /dev/null > /dev/null 2>&1 &
kd ap open $file > /dev/null
#kd app vol $vol > /dev/null
