#!/bin/bash
#
# Copyright (C) 2014 Wenva <lvyexuwenfa100@126.com>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is furnished
# to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e

spushd() {
     pushd "$1" 2>&1> /dev/null
}

spopd() {
     popd 2>&1> /dev/null
}

info() {
     local green="\033[1;32m"
     local normal="\033[0m"
     echo -e "[${green}INFO${normal}] $1"
}

error() {
     local red="\033[1;31m"
     local normal="\033[0m"
     echo -e "[${red}ERROR${normal}] $1"
}

# 获取当前目录
current_dir() {
    if [ ${0:0:1} = '/' ] || [ ${0:0:1} = '~' ]; then
        echo "$(dirname $0)"
    else
        echo "`pwd`/$(dirname $0)"
    fi
}

usage() {
cat << EOF

USAGE: $0 [-h] city

DESCRIPTION:

return whether info

OPTIONS:
    -h                Show this help message and exit

EOF
exit
}

while getopts 'h' arg; do
    case $arg in
        h)
            usage;;
        ?)
            usage;;
    esac
done

shift $(($OPTIND - 1))

source /etc/profile.d/robot.sh

city=$HEWHETHER_CITY

whether=`curl -s "https://free-api.heweather.com/v5/now?city=$city&key=$HEWHETHER_KEY"|jshon -e HeWeather5 -e 0 -e now`
cond=`echo $whether|jshon -e cond -e txt|sed 's/"//g'`
tmp=`echo $whether|jshon -e tmp|sed 's/"//g'`
suggestion=`curl -s "https://free-api.heweather.com/v5/suggestion?city=$city&key=$HEWHETHER_KEY"|jshon -e HeWeather5 -e 0 -e suggestion`
comf=`echo -n $suggestion|jshon -e comf -e txt|sed 's/"//g'`
drsg=`echo -n $suggestion|jshon -e drsg -e txt|sed 's/"//g'`
flu=`echo -n $suggestion|jshon -e flu -e txt|sed 's/"//g'`
sport=`echo -n $suggestion|jshon -e sport -e txt|sed 's/"//g'`
trav=`echo -n $suggestion|jshon -e trav -e txt|sed 's/"//g'`
uv=`echo -n $suggestion|jshon -e uv -e txt|sed 's/"//g'`
week=`date +星期%w|sed 'y/12345670/一二三四五六日日/'`
echo "今天是`date +%Y年%-m月%-d号`$week $cond $tmp摄氏度 舒适度指数:$comf 穿衣指数:$drsg 感冒指数:$flu 运动指数:$sport 出行指数:$trav 紫外线指数:$uv"


